import { AppRouteEnum } from '../../../app-route.enum'
import { EventAuthorityEnum } from '../../util-model/enumeration/event-authority.enum'
import { UserAuthorityEnum } from '../../util-model/enumeration/user-authority.enum'
import { ContextConfigModel } from '../model/context-config.model'
import { EventProfileActionEnum } from '../../util-model/enumeration/event-profile-action.enum'
import { UserActionEnum } from '../../../domains/user/data/state/user.action'
import { ParticipantActionEnum } from '../../../domains/participant/data/state/participant.action'
import { definePreset } from '@primeng/themes'
import Lara from '@primeng/themes/lara'
import { GroupActionEnum } from '../../../domains/group/data/state/group.action'
import { RegistryActionEnum } from '../../util-common/state/registry.action'
import { VehicleActionEnum } from '../../../domains/vehicle/data/state/vehicle.action'
import { ActivityActionEnum } from '../../../domains/activity/data/state/activity.action'
import { EventActionEnum } from '../../../domains/event/data/state/event.action'
import { MovementActionEnum } from '../../../domains/movement/data/state/movement.action'

export const sgdfConfig: ContextConfigModel = {
    theme: definePreset( Lara, {
        semantic: {
            primary: {
                '50': '#eef9ff',
                '100': '#dcf4ff',
                '200': '#b2ebff',
                '300': '#6ddcff',
                '400': '#20cbff',
                '500': '#00b5ff',
                '600': '#0091df',
                '700': '#0073b4',
                '800': '#006295',
                '900': '#00507a',
                '950': '#003a5d',
            },
            colorScheme: {
                light: {
                    primary: {
                        color: '#003a5d',
                        inverseColor: '#eef9ff',
                        hoverColor: '#00507a',
                        activeColor: '#006295',
                    },
                    highlight: {
                        background: '#003a5d',
                        focusBackground: '#0073b4',
                        color: '#ffffff',
                        focusColor: '#ffffff',
                    },
                },
                dark: {
                    primary: {
                        color: '#eef9ff',
                        inverseColor: '#003a5d',
                        hoverColor: '#dcf4ff',
                        activeColor: '#b2ebff',
                    },
                    highlight: {
                        background: 'rgba(250, 250, 250, .16)',
                        focusBackground: 'rgba(250, 250, 250, .24)',
                        color: 'rgba(255,255,255,.87)',
                        focusColor: 'rgba(255,255,255,.87)',
                    },
                },
            },
        },
        components: {
            card: {
                colorScheme: {
                    light: {
                        background: '#f8fafc',
                    },
                    dark: {
                        background: '#27272a',
                    },
                },
                body: {
                    padding: '1rem',
                },
            },
            dataview: {
                header: {
                    padding: 0,
                },
            },
            drawer: {
                background: '#003a5d',
                color: '#eef9ff',
                border: {
                    color: 'transparent',
                },
            },
            menu: {
                item: {
                    padding: 0,
                },
            },
            popover: {
                content: {
                    padding: 0,
                },
            },
            tabs: {
                tabpanel: {
                    padding: '1rem 0',
                },
            },
        },
    } ),
    logo: {
        light: 'img/SGDF/logo-white.svg',
        dark: 'img/SGDF/logo-white.svg',
    },
    defaultLanguage: 'fr-FR',
    maintainerEmail: 'laucoin@sgdf.fr',
    menu: [
        {
            name: 'global.menu.home',
            icon: 'pi pi-home',
            route: AppRouteEnum.HOME,
            requiredUserAuthority: undefined,
            requiredEventAuthority: undefined,
            requiredEventOption: undefined,
            enabled: true,
        },
        {
            name: 'global.menu.users',
            icon: 'pi pi-users',
            route: AppRouteEnum.USERS,
            requiredUserAuthority: UserAuthorityEnum.REGISTRY_USER_R,
            requiredEventAuthority: undefined,
            requiredEventOption: undefined,
            enabled: true,
        },
        {
            name: 'global.menu.events',
            icon: 'pi pi-calendar',
            route: AppRouteEnum.EVENTS,
            requiredUserAuthority: undefined,
            requiredEventAuthority: undefined,
            requiredEventOption: undefined,
            enabled: true,
        },
        {
            name: 'global.menu.event-profiles',
            icon: 'pi pi-user',
            route: AppRouteEnum.PROFILES,
            requiredUserAuthority: undefined,
            requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PROFILE_R,
            requiredEventOption: undefined,
            enabled: true,
        },
        {
            name: 'global.menu.movements',
            icon: 'pi pi-sort-alt',
            route: AppRouteEnum.MOVEMENTS,
            requiredUserAuthority: undefined,
            requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_MOVEMENT_R,
            requiredEventOption: undefined,
            enabled: true,
        },
        {
            name: 'global.menu.participants',
            icon: 'pi pi-users',
            route: AppRouteEnum.PARTICIPANTS,
            requiredUserAuthority: undefined,
            requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PARTICIPANT_R,
            requiredEventOption: undefined,
            enabled: true,
        },
        {
            name: 'global.menu.groups',
            icon: 'pi pi-sitemap',
            route: AppRouteEnum.GROUPS,
            requiredUserAuthority: undefined,
            requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_GROUP_R,
            requiredEventOption: undefined,
            enabled: true,
        },
        {
            name: 'global.menu.vehicles',
            icon: 'pi pi-car',
            route: AppRouteEnum.VEHICLES,
            requiredUserAuthority: undefined,
            requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_VEHICLE_R,
            requiredEventOption: 'VEHICLE',
            enabled: true,
        },
        {
            name: 'global.menu.activities',
            icon: 'pi pi-hammer',
            route: AppRouteEnum.ACTIVITIES,
            requiredUserAuthority: undefined,
            requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_ACTIVITY_R,
            requiredEventOption: 'ACTIVITY',
            enabled: true,
        },
    ],
    event: {
        optionIcons: new Map( [
            [ 'TICKETING', 'pi pi-ticket' ],
            [ 'VEHICLE', 'pi pi-car' ],
            [ 'ACTIVITY', 'pi pi-hammer' ],
            [ 'PHONE_COMMUNICATION', 'pi pi-phone' ],
            [ 'ACTIVITY_COMMUNICATION', 'pi pi-microphone' ],
            [ 'FIRE_RISK', 'pi pi-exclamation-triangle' ],
            [ 'SMOKE_REPORT', 'pi pi-cloud' ],
            [ 'MOVEMENT_REPORT', 'pi pi-sort-alt-slash' ],
        ] ),
        action: [
            {
                id: RegistryActionEnum.SELECT_USER_EVENT_PROFILE_BY_EVENT,
                name: 'events.actions.select',
                icon: 'pi pi-arrow-right',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: undefined,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'events.actions.confirmations.select.title',
                    message: 'events.actions.confirmations.select.message',
                    icon: 'pi pi-info-circle',
                    acceptSeverity: 'success',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: RegistryActionEnum.CREATE_SUPPORT_EVENT_PROFILE,
                name: 'events.actions.create-support',
                icon: 'pi pi-user-plus',
                disabled: false,
                requiredUserAuthority: UserAuthorityEnum.REGISTRY_PROFILE_C,
                requiredEventAuthority: undefined,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'events.actions.confirmations.create-support.title',
                    message: 'events.actions.confirmations.create-support.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: EventActionEnum.UPDATE_EVENT,
                name: 'events.actions.edit',
                icon: 'pi pi-pen-to-square',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_U,
                requiredEventOption: undefined,
                confirmation: undefined,
            },
            {
                id: EventActionEnum.DISABLE_EVENT,
                name: 'events.actions.disable',
                icon: 'pi pi-eye-slash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'events.actions.confirmations.disable.title',
                    message: 'events.actions.confirmations.disable.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: EventActionEnum.ENABLE_EVENT,
                name: 'events.actions.enable',
                icon: 'pi pi-replay',
                disabled: true,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'events.actions.confirmations.enable.title',
                    message: 'events.actions.confirmations.enable.message',
                    icon: 'pi pi-info-circle',
                    acceptSeverity: 'success',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: EventActionEnum.DELETE_EVENT,
                name: 'events.actions.delete',
                icon: 'pi pi-trash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_D,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'events.actions.confirmations.delete.title',
                    message: 'events.actions.confirmations.delete.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'danger',
                    rejectSeverity: 'secondary',
                    confirmProperty: 'name',
                },
            },
        ],
    },
    profile: {
        event: {
            action: [
                {
                    id: EventProfileActionEnum.SELECT_EVENT_PROFILE,
                    name: 'event-profiles.actions.select',
                    icon: 'pi pi-arrow-right',
                    disabled: false,
                    requiredUserAuthority: undefined,
                    requiredEventAuthority: undefined,
                    requiredEventOption: undefined,
                    confirmation: {
                        header: 'event-profiles.actions.confirmations.select.title',
                        message: 'event-profiles.actions.confirmations.select.message',
                        icon: 'pi pi-info-circle',
                        acceptSeverity: 'success',
                        rejectSeverity: 'secondary',
                        confirmProperty: undefined,
                    },
                },
                {
                    id: EventProfileActionEnum.UPDATE_EVENT_PROFILE,
                    name: 'event-profiles.actions.edit',
                    icon: 'pi pi-pen-to-square',
                    disabled: false,
                    requiredUserAuthority: undefined,
                    requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PROFILE_U,
                    requiredEventOption: undefined,
                    confirmation: undefined,
                },
                {
                    id: EventProfileActionEnum.BLOCK_EVENT_PROFILE,
                    name: 'event-profiles.actions.disable',
                    icon: 'pi pi-ban',
                    disabled: false,
                    requiredUserAuthority: undefined,
                    requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PROFILE_U,
                    requiredEventOption: undefined,
                    confirmation: {
                        header: 'event-profiles.actions.confirmations.disable.title',
                        message: 'event-profiles.actions.confirmations.disable.message',
                        icon: 'pi pi-exclamation-triangle',
                        acceptSeverity: 'warn',
                        rejectSeverity: 'secondary',
                        confirmProperty: undefined,
                    },
                },
                {
                    id: EventProfileActionEnum.UNBLOCK_EVENT_PROFILE,
                    name: 'event-profiles.actions.enable',
                    icon: 'pi pi-replay',
                    disabled: false,
                    requiredUserAuthority: undefined,
                    requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PROFILE_U,
                    requiredEventOption: undefined,
                    confirmation: {
                        header: 'event-profiles.actions.confirmations.enable.title',
                        message: 'event-profiles.actions.confirmations.enable.message',
                        icon: 'pi pi-exclamation-triangle',
                        acceptSeverity: 'success',
                        rejectSeverity: 'secondary',
                        confirmProperty: undefined,
                    },
                },
                {
                    id: EventProfileActionEnum.DELETE_EVENT_PROFILE,
                    name: 'event-profiles.actions.delete',
                    icon: 'pi pi-trash',
                    disabled: false,
                    requiredUserAuthority: undefined,
                    requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PROFILE_D,
                    requiredEventOption: undefined,
                    confirmation: {
                        header: 'event-profiles.actions.confirmations.delete.title',
                        message: 'event-profiles.actions.confirmations.delete.message',
                        icon: 'pi pi-exclamation-triangle',
                        acceptSeverity: 'danger',
                        rejectSeverity: 'secondary',
                        confirmProperty: undefined,
                    },
                },
            ],
        },
    },
    vehicle: {
        action: [
            {
                id: VehicleActionEnum.FETCH_VEHICLE_MOVEMENTS_PAGE,
                name: 'vehicles.actions.movements-history',
                icon: 'pi pi-history',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_VEHICLE_HISTORY_R,
                requiredEventOption: 'VEHICLE',
                confirmation: undefined,
            },
            {
                id: VehicleActionEnum.UPDATE_VEHICLE,
                name: 'vehicles.actions.edit',
                icon: 'pi pi-pen-to-square',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_VEHICLE_U,
                requiredEventOption: 'VEHICLE',
                confirmation: undefined,
            },
            {
                id: VehicleActionEnum.DISABLE_VEHICLE,
                name: 'vehicles.actions.disable',
                icon: 'pi pi-eye-slash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_VEHICLE_U,
                requiredEventOption: 'VEHICLE',
                confirmation: {
                    header: 'vehicles.actions.confirmations.disable.title',
                    message: 'vehicles.actions.confirmations.disable.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: VehicleActionEnum.ENABLE_VEHICLE,
                name: 'vehicles.actions.enable',
                icon: 'pi pi-replay',
                disabled: true,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_VEHICLE_U,
                requiredEventOption: 'VEHICLE',
                confirmation: {
                    header: 'vehicles.actions.confirmations.enable.title',
                    message: 'vehicles.actions.confirmations.enable.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: VehicleActionEnum.DELETE_VEHICLE,
                name: 'vehicles.actions.delete',
                icon: 'pi pi-trash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_VEHICLE_D,
                requiredEventOption: 'VEHICLE',
                confirmation: {
                    header: 'vehicles.actions.confirmations.delete.title',
                    message: 'vehicles.actions.confirmations.delete.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'danger',
                    rejectSeverity: 'secondary',
                    confirmProperty: 'licensePlate',
                },
            },
        ],
    },
    activity: {
        action: [
            {
                id: ActivityActionEnum.FETCH_ACTIVITY_MOVEMENTS_PAGE,
                name: 'activities.actions.movements-history',
                icon: 'pi pi-history',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_ACTIVITY_HISTORY_R,
                requiredEventOption: 'ACTIVITY',
                confirmation: undefined,
            },
            {
                id: ActivityActionEnum.UPDATE_ACTIVITY,
                name: 'activities.actions.edit',
                icon: 'pi pi-pen-to-square',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_ACTIVITY_U,
                requiredEventOption: 'ACTIVITY',
                confirmation: undefined,
            },
            {
                id: ActivityActionEnum.DISABLE_ACTIVITY,
                name: 'activities.actions.disable',
                icon: 'pi pi-eye-slash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_ACTIVITY_U,
                requiredEventOption: 'ACTIVITY',
                confirmation: {
                    header: 'activities.actions.confirmations.disable.title',
                    message: 'activities.actions.confirmations.disable.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: ActivityActionEnum.ENABLE_ACTIVITY,
                name: 'activities.actions.enable',
                icon: 'pi pi-replay',
                disabled: true,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_ACTIVITY_U,
                requiredEventOption: 'ACTIVITY',
                confirmation: {
                    header: 'activities.actions.confirmations.enable.title',
                    message: 'activities.actions.confirmations.enable.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: ActivityActionEnum.DELETE_ACTIVITY,
                name: 'activities.actions.delete',
                icon: 'pi pi-trash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_ACTIVITY_D,
                requiredEventOption: 'ACTIVITY',
                confirmation: {
                    header: 'activities.actions.confirmations.delete.title',
                    message: 'activities.actions.confirmations.delete.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'danger',
                    rejectSeverity: 'secondary',
                    confirmProperty: 'name',
                },
            },
        ],
    },
    participant: {
        action: [
            {
                id: ParticipantActionEnum.FETCH_PARTICIPANT_MOVEMENTS_PAGE,
                name: 'participants.actions.movements-history',
                icon: 'pi pi-history',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PARTICIPANT_HISTORY_R,
                requiredEventOption: undefined,
                confirmation: undefined,
            },
            {
                id: ParticipantActionEnum.UPDATE_PARTICIPANT,
                name: 'participants.actions.edit',
                icon: 'pi pi-pen-to-square',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PARTICIPANT_U,
                requiredEventOption: undefined,
                confirmation: undefined,
            },
            {
                id: ParticipantActionEnum.DISABLE_PARTICIPANT,
                name: 'participants.actions.disable',
                icon: 'pi pi-eye-slash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PARTICIPANT_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'participants.actions.confirmations.disable.title',
                    message: 'participants.actions.confirmations.disable.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: ParticipantActionEnum.ENABLE_PARTICIPANT,
                name: 'participants.actions.enable',
                icon: 'pi pi-replay',
                disabled: true,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PARTICIPANT_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'participants.actions.confirmations.enable.title',
                    message: 'participants.actions.confirmations.enable.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: GroupActionEnum.REMOVE_MEMBER_FROM_GROUP,
                name: 'participants.actions.remove-member',
                icon: 'pi pi-user-minus',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_GROUP_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'participants.actions.confirmations.remove-member.title',
                    message: 'participants.actions.confirmations.remove-member.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: ParticipantActionEnum.DELETE_PARTICIPANT,
                name: 'participants.actions.delete',
                icon: 'pi pi-trash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PARTICIPANT_D,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'participants.actions.confirmations.delete.title',
                    message: 'participants.actions.confirmations.delete.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'danger',
                    rejectSeverity: 'secondary',
                    confirmProperty: 'firstName',
                },
            },
        ],
    },
    group: {
        action: [
            {
                id: GroupActionEnum.FETCH_GROUP_MEMBERS_PAGE,
                name: 'groups.actions.members',
                icon: 'pi pi-users',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_GROUP_R,
                requiredEventOption: undefined,
                confirmation: undefined,
            },
            {
                id: GroupActionEnum.UPDATE_GROUP,
                name: 'groups.actions.edit',
                icon: 'pi pi-pen-to-square',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_GROUP_U,
                requiredEventOption: undefined,
                confirmation: undefined,
            },
            {
                id: GroupActionEnum.DISABLE_GROUP,
                name: 'groups.actions.disable',
                icon: 'pi pi-eye-slash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_GROUP_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'groups.actions.confirmations.disable.title',
                    message: 'groups.actions.confirmations.disable.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: GroupActionEnum.ENABLE_GROUP,
                name: 'groups.actions.enable',
                icon: 'pi pi-replay',
                disabled: true,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_GROUP_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'groups.actions.confirmations.enable.title',
                    message: 'groups.actions.confirmations.enable.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: GroupActionEnum.DELETE_GROUP,
                name: 'groups.actions.delete',
                icon: 'pi pi-trash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_GROUP_D,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'groups.actions.confirmations.delete.title',
                    message: 'groups.actions.confirmations.delete.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'danger',
                    rejectSeverity: 'secondary',
                    confirmProperty: 'name',
                },
            },
        ],
    },
    movement: {
        action: [
            {
                id: MovementActionEnum.UPDATE_MOVEMENT,
                name: 'movements.actions.edit',
                icon: 'pi pi-pen-to-square',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_MOVEMENT_U,
                requiredEventOption: undefined,
                confirmation: undefined,
            },
            {
                id: MovementActionEnum.DISABLE_MOVEMENT,
                name: 'movements.actions.disable',
                icon: 'pi pi-eye-slash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_MOVEMENT_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'movements.actions.confirmations.disable.title',
                    message: 'movements.actions.confirmations.disable.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: MovementActionEnum.ENABLE_MOVEMENT,
                name: 'movements.actions.enable',
                icon: 'pi pi-replay',
                disabled: true,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_MOVEMENT_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'movements.actions.confirmations.enable.title',
                    message: 'movements.actions.confirmations.enable.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: MovementActionEnum.DELETE_MOVEMENT,
                name: 'movements.actions.delete',
                icon: 'pi pi-trash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_MOVEMENT_D,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'movements.actions.confirmations.delete.title',
                    message: 'movements.actions.confirmations.delete.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'danger',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
        ],
    },
    user: {
        myAction: [
            {
                id: RegistryActionEnum.IMPERSONATE_CURRENT_USER,
                name: 'users.actions.impersonate',
                icon: 'pi pi-eraser',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: undefined,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'users.actions.confirmations.impersonate.myself.title',
                    message: 'users.actions.confirmations.impersonate.myself.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'danger',
                    rejectSeverity: 'secondary',
                    confirmProperty: 'firstName',
                },
            },
        ],
        action: [
            {
                id: UserActionEnum.UPDATE_USER_ROLE,
                name: 'users.actions.update-role',
                icon: 'pi pi-user-edit',
                disabled: false,
                requiredUserAuthority: UserAuthorityEnum.REGISTRY_USER_U,
                requiredEventAuthority: undefined,
                requiredEventOption: undefined,
                confirmation: undefined,
            },
            {
                id: UserActionEnum.BLOCK_USER,
                name: 'users.actions.disable',
                icon: 'pi pi-ban',
                disabled: false,
                requiredUserAuthority: UserAuthorityEnum.REGISTRY_USER_U,
                requiredEventAuthority: undefined,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'users.actions.confirmations.disable.title',
                    message: 'users.actions.confirmations.disable.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: UserActionEnum.UNBLOCK_USER,
                name: 'users.actions.enable',
                icon: 'pi pi-replay',
                disabled: true,
                requiredUserAuthority: UserAuthorityEnum.REGISTRY_USER_U,
                requiredEventAuthority: undefined,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'users.actions.confirmations.enable.title',
                    message: 'users.actions.confirmations.enable.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: UserActionEnum.IMPERSONATE_USER,
                name: 'users.actions.impersonate',
                icon: 'pi pi-eraser',
                disabled: false,
                requiredUserAuthority: UserAuthorityEnum.REGISTRY_USER_D,
                requiredEventAuthority: undefined,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'users.actions.confirmations.impersonate.other.title',
                    message: 'users.actions.confirmations.impersonate.other.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'danger',
                    rejectSeverity: 'secondary',
                    confirmProperty: 'firstName',
                },
            },
            {
                id: UserActionEnum.DELETE_USER,
                name: 'users.actions.delete',
                icon: 'pi pi-trash',
                disabled: false,
                requiredUserAuthority: UserAuthorityEnum.REGISTRY_USER_D,
                requiredEventAuthority: undefined,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'users.actions.confirmations.delete.title',
                    message: 'users.actions.confirmations.delete.message',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'danger',
                    rejectSeverity: 'secondary',
                    confirmProperty: 'firstName',
                },
            },
        ],
    },
    notification: {
        duration: {
            info: 5000,
            success: 3000,
            warn: 8000,
            secondary: 5000,
            contrast: 5000,
        },
    },
}
