import { AppRouteEnum } from '../../../app-route.enum'
import { EventAuthorityEnum } from '../../util-model/enumeration/event-authority.enum'
import { UserAuthorityEnum } from '../../util-model/enumeration/user-authority.enum'
import { ContextConfigModel } from '../model/context-config.model'
import { EventActionEnum } from '../../../domains/event/data/state/event.action'
import { EventProfileActionEnum } from '../../util-model/enumeration/event-profile-action.enum'
import { UserActionEnum } from '../../../domains/user/data/state/user.action'
import { ParticipantActionEnum } from '../../../domains/participant/data/state/participant.action'
import { MovementActionEnum } from '../../../domains/movement/data/state/movement.action'
import { definePreset } from '@primeng/themes'
import Lara from '@primeng/themes/lara'
import { GroupActionEnum } from '../../../domains/group/data/state/group.action'
import { RegistryActionEnum } from '../../util-common/state/registry.action'

export const sgdfConfig: ContextConfigModel = {
    theme: definePreset( Lara, {
        semantic: {
            primary: {
                '50': '#eef9ff',
                '100': '#dcf4ff',
                '200': '#b2ebff',
                '300': '#6ddcff',
                '400': '#20cbff',
                '500': '#00b5ff',
                '600': '#0091df',
                '700': '#0073b4',
                '800': '#006295',
                '900': '#00507a',
                '950': '#003a5d',
            },
            colorScheme: {
                light: {
                    primary: {
                        color: '#003a5d',
                        inverseColor: '#eef9ff',
                        hoverColor: '#00507a',
                        activeColor: '#006295',
                    },
                    highlight: {
                        background: '#003a5d',
                        focusBackground: '#0073b4',
                        color: '#ffffff',
                        focusColor: '#ffffff',
                    },
                },
                dark: {
                    primary: {
                        color: '#eef9ff',
                        inverseColor: '#003a5d',
                        hoverColor: '#dcf4ff',
                        activeColor: '#b2ebff',
                    },
                    highlight: {
                        background: 'rgba(250, 250, 250, .16)',
                        focusBackground: 'rgba(250, 250, 250, .24)',
                        color: 'rgba(255,255,255,.87)',
                        focusColor: 'rgba(255,255,255,.87)',
                    },
                },
            },
        },
        components: {
            card: {
                colorScheme: {
                    light: {
                        background: '#f8fafc',
                    },
                    dark: {
                        background: '#27272a',
                    },
                },
                body: {
                    padding: '1rem',
                },
            },
            dataview: {
                header: {
                    padding: 0,
                },
            },
            drawer: {
                background: '#003a5d',
                color: '#eef9ff',
                border: {
                    color: 'transparent',
                },
            },
            menu: {
                item: {
                    padding: 0,
                },
            },
            popover: {
                content: {
                    padding: 0,
                },
            },
            tabs: {
                tabpanel: {
                    padding: '1rem 0',
                },
            },
        },
    } ),
    logo: {
        light: 'img/SGDF/logo-white.svg',
        dark: 'img/SGDF/logo-white.svg',
    },
    defaultLanguage: 'fr-FR',
    maintainerEmail: 'laucoin@sgdf.fr',
    menu: [
        {
            name: 'menu.users',
            icon: 'pi pi-users',
            route: AppRouteEnum.USERS,
            requiredUserAuthority: UserAuthorityEnum.REGISTRY_USER_R,
            requiredEventAuthority: undefined,
            requiredEventOption: undefined,
            enabled: true,
        },
        {
            name: 'menu.events',
            icon: 'pi pi-calendar',
            route: AppRouteEnum.EVENTS,
            requiredUserAuthority: undefined,
            requiredEventAuthority: undefined,
            requiredEventOption: undefined,
            enabled: true,
        },
        {
            name: 'menu.profiles',
            icon: 'pi pi-user',
            route: AppRouteEnum.PROFILES,
            requiredUserAuthority: undefined,
            requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PROFILE_R,
            requiredEventOption: undefined,
            enabled: true,
        },
        {
            name: 'menu.movements',
            icon: 'pi pi-sort-alt',
            route: AppRouteEnum.MOVEMENTS,
            requiredUserAuthority: undefined,
            requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_MOVEMENT_R,
            requiredEventOption: undefined,
            enabled: true,
        },
        {
            name: 'menu.participants',
            icon: 'pi pi-users',
            route: AppRouteEnum.PARTICIPANTS,
            requiredUserAuthority: undefined,
            requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PARTICIPANT_R,
            requiredEventOption: undefined,
            enabled: true,
        },
        {
            name: 'menu.groups',
            icon: 'pi pi-sitemap',
            route: AppRouteEnum.GROUPS,
            requiredUserAuthority: undefined,
            requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_GROUP_R,
            requiredEventOption: undefined,
            enabled: true,
        },
    ],
    event: {
        optionIcons: new Map( [
            [ 'TICKETING', 'pi pi-ticket' ],
            [ 'VEHICLE', 'pi pi-car' ],
            [ 'ACTIVITY', 'pi pi-hammer' ],
            [ 'PHONE_COMMUNICATION', 'pi pi-phone' ],
            [ 'ACTIVITY_COMMUNICATION', 'pi pi-microphone' ],
            [ 'FIRE_RISK', 'pi pi-exclamation-triangle' ],
            [ 'SMOKE_REPORT', 'pi pi-cloud' ],
            [ 'MOVEMENT_REPORT', 'pi pi-sort-alt-slash' ],
        ] ),
        action: [
            {
                id: EventActionEnum.UPDATE_EVENT,
                name: 'event.action.edit',
                icon: 'pi pi-pen-to-square',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_U,
                requiredEventOption: undefined,
                confirmation: undefined,
            },
            {
                id: EventActionEnum.DISABLE_EVENT,
                name: 'event.action.disable',
                icon: 'pi pi-eye-slash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'event.action.confirmation.title.disable',
                    message: 'event.action.confirmation.message.disable',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: EventActionEnum.ENABLE_EVENT,
                name: 'event.action.enable',
                icon: 'pi pi-replay',
                disabled: true,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'event.action.confirmation.title.enable',
                    message: 'event.action.confirmation.message.enable',
                    icon: 'pi pi-info-circle',
                    acceptSeverity: 'success',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: EventActionEnum.DELETE_EVENT,
                name: 'event.action.delete',
                icon: 'pi pi-trash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_D,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'event.action.confirmation.title.delete',
                    message: 'event.action.confirmation.message.delete',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'danger',
                    rejectSeverity: 'secondary',
                    confirmProperty: 'name',
                },
            },
        ],
    },
    profile: {
        event: {
            action: [
                {
                    id: EventProfileActionEnum.SELECT_EVENT_PROFILE,
                    name: 'profile.action.select',
                    icon: undefined,
                    disabled: false,
                    requiredUserAuthority: undefined,
                    requiredEventAuthority: undefined,
                    requiredEventOption: undefined,
                    confirmation: {
                        header: 'profile.action.confirmation.title.select',
                        message: 'profile.action.confirmation.message.select',
                        icon: 'pi pi-info-circle',
                        acceptSeverity: 'success',
                        rejectSeverity: 'secondary',
                        confirmProperty: undefined,
                    },
                },
                {
                    id: EventProfileActionEnum.UPDATE_EVENT_PROFILE,
                    name: 'profile.action.edit',
                    icon: 'pi pi-pen-to-square',
                    disabled: false,
                    requiredUserAuthority: undefined,
                    requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PROFILE_U,
                    requiredEventOption: undefined,
                    confirmation: undefined,
                },
                {
                    id: EventProfileActionEnum.BLOCK_EVENT_PROFILE,
                    name: 'profile.action.block',
                    icon: 'pi pi-ban',
                    disabled: false,
                    requiredUserAuthority: undefined,
                    requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PROFILE_U,
                    requiredEventOption: undefined,
                    confirmation: {
                        header: 'profile.action.confirmation.title.block',
                        message: 'profile.action.confirmation.message.block',
                        icon: 'pi pi-exclamation-triangle',
                        acceptSeverity: 'warn',
                        rejectSeverity: 'secondary',
                        confirmProperty: undefined,
                    },
                },
                {
                    id: EventProfileActionEnum.UNBLOCK_EVENT_PROFILE,
                    name: 'profile.action.unblock',
                    icon: 'pi pi-replay',
                    disabled: false,
                    requiredUserAuthority: undefined,
                    requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PROFILE_U,
                    requiredEventOption: undefined,
                    confirmation: {
                        header: 'profile.action.confirmation.title.unblock',
                        message: 'profile.action.confirmation.message.unblock',
                        icon: 'pi pi-exclamation-triangle',
                        acceptSeverity: 'success',
                        rejectSeverity: 'secondary',
                        confirmProperty: undefined,
                    },
                },
                {
                    id: EventProfileActionEnum.DELETE_EVENT_PROFILE,
                    name: 'profile.action.delete',
                    icon: 'pi pi-trash',
                    disabled: false,
                    requiredUserAuthority: undefined,
                    requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PROFILE_D,
                    requiredEventOption: undefined,
                    confirmation: {
                        header: 'profile.action.confirmation.title.delete',
                        message: 'profile.action.confirmation.message.delete',
                        icon: 'pi pi-exclamation-triangle',
                        acceptSeverity: 'danger',
                        rejectSeverity: 'secondary',
                        confirmProperty: undefined,
                    },
                },
            ],
        },
    },
    participant: {
        action: [
            {
                id: ParticipantActionEnum.UPDATE_PARTICIPANT,
                name: 'participant.action.edit',
                icon: 'pi pi-pen-to-square',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PARTICIPANT_U,
                requiredEventOption: undefined,
                confirmation: undefined,
            },
            {
                id: GroupActionEnum.REMOVE_MEMBER_FROM_GROUP,
                name: 'group.action.remove-member',
                icon: 'pi pi-user-minus',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_GROUP_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'group.action.confirmation.title.remove-member',
                    message: 'group.action.confirmation.message.remove-member',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: ParticipantActionEnum.DISABLE_PARTICIPANT,
                name: 'participant.action.disable',
                icon: 'pi pi-eye-slash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PARTICIPANT_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'participant.action.confirmation.title.disable',
                    message: 'participant.action.confirmation.message.disable',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: ParticipantActionEnum.ENABLE_PARTICIPANT,
                name: 'participant.action.enable',
                icon: 'pi pi-replay',
                disabled: true,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PARTICIPANT_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'participant.action.confirmation.title.enable',
                    message: 'participant.action.confirmation.message.enable',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: ParticipantActionEnum.DELETE_PARTICIPANT,
                name: 'participant.action.delete',
                icon: 'pi pi-trash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_PARTICIPANT_D,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'participant.action.confirmation.title.delete',
                    message: 'participant.action.confirmation.message.delete',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'danger',
                    rejectSeverity: 'secondary',
                    confirmProperty: 'firstName',
                },
            },
        ],
    },
    group: {
        action: [
            {
                id: GroupActionEnum.FETCH_GROUP_MEMBER_PAGE,
                name: 'group.action.members',
                icon: 'pi pi-users',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_GROUP_R,
                requiredEventOption: undefined,
                confirmation: undefined,
            },
            {
                id: GroupActionEnum.UPDATE_GROUP,
                name: 'group.action.edit',
                icon: 'pi pi-pen-to-square',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_GROUP_U,
                requiredEventOption: undefined,
                confirmation: undefined,
            },
            {
                id: GroupActionEnum.DISABLE_GROUP,
                name: 'group.action.disable',
                icon: 'pi pi-eye-slash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_GROUP_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'group.action.confirmation.title.disable',
                    message: 'group.action.confirmation.message.disable',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: GroupActionEnum.ENABLE_GROUP,
                name: 'group.action.enable',
                icon: 'pi pi-replay',
                disabled: true,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_GROUP_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'group.action.confirmation.title.enable',
                    message: 'group.action.confirmation.message.enable',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: GroupActionEnum.DELETE_GROUP,
                name: 'group.action.delete',
                icon: 'pi pi-trash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_GROUP_D,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'group.action.confirmation.title.delete',
                    message: 'group.action.confirmation.message.delete',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'danger',
                    rejectSeverity: 'secondary',
                    confirmProperty: 'name',
                },
            },
        ],
    },
    movement: {
        action: [
            {
                id: MovementActionEnum.UPDATE_MOVEMENT,
                name: 'movement.action.edit',
                icon: 'pi pi-pen-to-square',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_MOVEMENT_U,
                requiredEventOption: undefined,
                confirmation: undefined,
            },
            {
                id: MovementActionEnum.DISABLE_MOVEMENT,
                name: 'movement.action.disable',
                icon: 'pi pi-eye-slash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_MOVEMENT_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'movement.action.confirmation.title.disable',
                    message: 'movement.action.confirmation.message.disable',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: MovementActionEnum.ENABLE_MOVEMENT,
                name: 'movement.action.enable',
                icon: 'pi pi-replay',
                disabled: true,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_MOVEMENT_U,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'movement.action.confirmation.title.enable',
                    message: 'movement.action.confirmation.message.enable',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: MovementActionEnum.DELETE_MOVEMENT,
                name: 'movement.action.delete',
                icon: 'pi pi-trash',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: EventAuthorityEnum.REGISTRY_EVENT_MOVEMENT_D,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'movement.action.confirmation.title.delete',
                    message: 'movement.action.confirmation.message.delete',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'danger',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
        ],
    },
    user: {
        myAction: [
            {
                id: RegistryActionEnum.IMPERSONATE_CURRENT_USER,
                name: 'user.action.impersonate',
                icon: 'pi pi-eraser',
                disabled: false,
                requiredUserAuthority: undefined,
                requiredEventAuthority: undefined,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'user.action.confirmation.title.impersonate-myself',
                    message: 'user.action.confirmation.message.impersonate-myself',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'danger',
                    rejectSeverity: 'secondary',
                    confirmProperty: 'firstName',
                },
            },
        ],
        action: [
            {
                id: UserActionEnum.UPDATE_USER_ROLE,
                name: 'user.action.update-role',
                icon: 'pi pi-user-edit',
                disabled: false,
                requiredUserAuthority: UserAuthorityEnum.REGISTRY_USER_U,
                requiredEventAuthority: undefined,
                requiredEventOption: undefined,
                confirmation: undefined,
            },
            {
                id: UserActionEnum.BLOCK_USER,
                name: 'user.action.block',
                icon: 'pi pi-ban',
                disabled: false,
                requiredUserAuthority: UserAuthorityEnum.REGISTRY_USER_U,
                requiredEventAuthority: undefined,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'user.action.confirmation.title.block',
                    message: 'user.action.confirmation.message.block',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: UserActionEnum.UNBLOCK_USER,
                name: 'user.action.unblock',
                icon: 'pi pi-replay',
                disabled: true,
                requiredUserAuthority: UserAuthorityEnum.REGISTRY_USER_U,
                requiredEventAuthority: undefined,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'user.action.confirmation.title.unblock',
                    message: 'user.action.confirmation.message.unblock',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'warn',
                    rejectSeverity: 'secondary',
                    confirmProperty: undefined,
                },
            },
            {
                id: UserActionEnum.IMPERSONATE_USER,
                name: 'user.action.impersonate',
                icon: 'pi pi-eraser',
                disabled: false,
                requiredUserAuthority: UserAuthorityEnum.REGISTRY_USER_D,
                requiredEventAuthority: undefined,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'user.action.confirmation.title.impersonate',
                    message: 'user.action.confirmation.message.impersonate',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'danger',
                    rejectSeverity: 'secondary',
                    confirmProperty: 'firstName',
                },
            },
            {
                id: UserActionEnum.DELETE_USER,
                name: 'user.action.delete',
                icon: 'pi pi-trash',
                disabled: false,
                requiredUserAuthority: UserAuthorityEnum.REGISTRY_USER_D,
                requiredEventAuthority: undefined,
                requiredEventOption: undefined,
                confirmation: {
                    header: 'user.action.confirmation.title.delete',
                    message: 'user.action.confirmation.message.delete',
                    icon: 'pi pi-exclamation-triangle',
                    acceptSeverity: 'danger',
                    rejectSeverity: 'secondary',
                    confirmProperty: 'firstName',
                },
            },
        ],
    },
    notification: {
        duration: {
            info: 5000,
            success: 3000,
            warn: 8000,
            secondary: 5000,
            contrast: 5000,
        },
    },
}
