export enum ProjectOptionEnum {
    ACTIVITY = 'ACTIVITY',
    PHONE_COMMUNICATION = 'PHONE_COMMUNICATION',
    ACTIVITY_COMMUNICATION = 'ACTIVITY_COMMUNICATION',
    SMOKE_REPORT = 'SMOKE_REPORT',
    MOVEMENT_REPORT = 'MOVEMENT_REPORT',
    TICKETING = 'TICKETING',
    VEHICLE = 'VEHICLE',
    FIRE_RISK = 'FIRE_RISK',
}
