export enum UserAuthorityEnum {
    REGISTRY_USER_R = 'REGISTRY_USER_R',
    REGISTRY_USER_U = 'REGISTRY_USER_U',
    REGISTRY_USER_D = 'REGISTRY_USER_D',
    REGISTRY_EVENT_C = 'REGISTRY_EVENT_C',
    REGISTRY_EVENT_R = 'REGISTRY_EVENT_R',
    REGISTRY_PROFILE_C = 'REGISTRY_PROFILE_C',
    REGISTRY_USER_METADATA_R = 'REGISTRY_USER_METADATA_R',
}
