export enum UserAuthorityEnum {
    REGISTRY_USER_R = 'REGISTRY_USER_R',
    REGISTRY_USER_METADATA_R = 'REGISTRY_USER_METADATA_R',
    REGISTRY_USER_U = 'REGISTRY_USER_U',
    REGISTRY_USER_D = 'REGISTRY_USER_D',
    REGISTRY_PROJECT_METADATA_R = 'REGISTRY_PROJECT_METADATA_R',
    REGISTRY_PROJECT_C = 'REGISTRY_PROJECT_C',
    REGISTRY_PROJECT_R = 'REGISTRY_PROJECT_R',
    REGISTRY_PROFILE_C = 'REGISTRY_PROFILE_C'
}
