export const CURRENT_USER_ID: string = '{{currentUserId}}'
export const SELECT_PROFILE_PROJECT_ID: string = '{{defaultProfileProjectId}}'
export const CSRF_COOKIE: string = 'XSRF-TOKEN'
export const CSRF_HEADER: string = 'X-XSRF-TOKEN'
export const REDIRECT_URI: string = 'redirect_uri'
export const LOCALE: string = 'locale'
