export enum UserAuthorityEnum {
    ROLE_REGISTRY_GLOBAL_USER_MANAGEMENT = 'ROLE_REGISTRY_GLOBAL_USER_MANAGEMENT',
    ROLE_REGISTRY_GLOBAL_SUPPORT_PROFILE = 'ROLE_REGISTRY_GLOBAL_SUPPORT_PROFILE',
}
